server:
  port: 1111
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.100:8191/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 30 #\u5FC3\u8DF3\u68C0\u6D4B\u68C0\u6D4B\u4E0E\u7EED\u7EA6\u65F6\u95F4
    lease-expiration-duration-in-seconds: 50 #\u6D4B\u8BD5\u65F6\u5C06\u503C\u8BBE\u7F6E\u8BBE\u7F6E\u5C0F\u4E9B\uFF0C\u4FDD\u8BC1\u670D\u52A1\u5173\u95ED\u540E\u6CE8\u518C\u4E2D\u5FC3\u80FD\u53CA\u65F6\u8E22\u51FA\u670D
    status-page-url-path: /hello
    health-check-url-path: /hello
spring:
  application:
    name: compute-service
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/trafficdata?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useUnicode=true&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: root
      #hikari连接池
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        connection-test-query: select 1
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000
        maximum-pool-size: 20
        minimum-idle: 20
        #spring.datasource.max-idle=10
        #指定连接池等待连接返回的最大等待时间，毫秒单位.
        #spring.datasource.max-wait=10000
        #指定必须保持连接的最小值
        #spring.datasource.min-idle=5
        #指定连接池中最大的活跃连接数.
        #spring.datasource.secondary.max-active=50
        #spring.datasource.initial-size=5
        #spring.datasource.validation-query=SELECT 1
        #spring.datasource.test-on-borrow=false
        #spring.datasource.test-while-idle=true
        #spring.datasource.time-between-eviction-runs-millis=18800
        #spring.datasource.jdbc-interceptors=ConnectionState;SlowQueryReport(threshold=0)
logging:
  config: classpath:log4j2.xml