server:
  port: 1111
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.100:8191/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 30 #心跳检测检测与续约时间
    lease-expiration-duration-in-seconds: 50 #测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服
    status-page-url-path: /hello
    health-check-url-path: /hello
spring:
  application:
    name: compute-service
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/trafficdata?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useUnicode=true&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: root
      #hikari连接池
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        connection-test-query: select 1
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000
        maximum-pool-size: 20
        minimum-idle: 20
        #spring.datasource.max-idle=10
        #指定连接池等待连接返回的最大等待时间，毫秒单位.
        #spring.datasource.max-wait=10000
        #指定必须保持连接的最小值
        #spring.datasource.min-idle=5
        #指定连接池中最大的活跃连接数.
        #spring.datasource.secondary.max-active=50
        #spring.datasource.initial-size=5
        #spring.datasource.validation-query=SELECT 1
        #spring.datasource.test-on-borrow=false
        #spring.datasource.test-while-idle=true
        #spring.datasource.time-between-eviction-runs-millis=18800
        #spring.datasource.jdbc-interceptors=ConnectionState;SlowQueryReport(threshold=0)
logging:
  config: classpath:log4j2.xml