server:
  port: 1112
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.106:8191/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 50
    status-page-url-path: /hello
    health-check-url-path: /hello
spring:
  application:
    name: product-service
logging:
  config: classpath:log4j2.xml