server:
  port: 8191  #端口
eureka:
  instance:
    prefer-ip-address: true #是否向服务器注册IP
    ip-address: ${spring.cloud.inetutils.default-ip-address}
    instance-id:  ${spring.cloud.inetutils.default-ip-address}:${server.port}
    hostname: ${spring.cloud.inetutils.default-ip-address}
  client:
    fetch-registry: false  #注册自己，用于集群形式
    register-with-eureka: false #若为true的话会报错
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enableSelfPreservation: false #关闭自我保护
spring:
  application:
    name: Eureka-Server #服务名称
  cloud:
    inetutils:
      default-ip-address: 127.0.0.1
      default-hostname: 127.0.0.1
      preferred-networks: 127.0.0.1
logging:
 config: classpath:log4j2.xml