server:
  port: 1113
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.106:8191/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-renewal-interval-in-seconds: 30 #心跳检测检测与续约时间
    lease-expiration-duration-in-seconds: 50 #测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服
    status-page-url-path: /hello
    health-check-url-path: /hello
spring:
  application:
    name: zuul-service
#routes to serviceId
zuul:
  routes:
    product-service:
     path: /product-service/**
     serviceId: product-service
     path: /compute-service/**
     serviceId: compute-service
     path: /ribbon-service/**
     serviceId: ribbon-service
     #routes to url
     product-service-url:
      path: /product-service-url/**
      url: http://localhost:1112/
     compute-service-url:
      path: /compute-service-url/**
      url: http://localhost:1111/
     ribbon-service-url:
      path: /ribbon-service-url/**
      url: http://localhost:1114/
